name: Deploy APP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Login docker Hub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build docker image
      run: docker build -t nayteixeira/app .
    - name: Push image docker
      run: docker push nayteixeira/app
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull nayteixeira/app:latest
      - name: Remove docker container
        run: docker rm -f app
      - name: Run docker container
        run: docker run -it -d -p 8000:8000 --name app app